<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;


class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('users')->insert([
            [
                'NIK' => '1234567890123456',
                'name' => 'Admin1',
                'phone_number' => '081234567890',
                'address' => 'Jl. Merdeka No. 1, Surabaya',
                'role' => 'admin',
                'birthdate' => null,
                'profile' => 'profile1.jpg',
                'email' => 'admin1@example.com',
                'email_verified_at' => '2023-01-02 12:00:00',
                'password' => Hash::make('123456789'),
                'google_id' => 'google_id_1',
                'google_token' => 'google_token_1',
                'google_refresh_token' => 'google_refresh_token_1',
                'remember_token' => 'remember_token_1',
                'created_at' => '2023-01-01 10:00:00',
                'updated_at' => '2023-01-01 10:00:00',
                'gender' => 'L'
            ],
            [
                'NIK' => '1234567890123456',
                'name' => 'Admin2',
                'phone_number' => '081234567890',
                'address' => 'Jl. Merdeka No. 1, Surabaya',
                'role' => 'admin',
                'birthdate' => null,
                'profile' => 'profile1.jpg',
                'email' => 'admin2@example.com',
                'email_verified_at' => '2023-01-02 12:00:00',
                'password' => Hash::make('123456789'),
                'google_id' => 'google_id_1',
                'google_token' => 'google_token_1',
                'google_refresh_token' => 'google_refresh_token_1',
                'remember_token' => 'remember_token_1',
                'created_at' => '2023-01-01 10:00:00',
                'updated_at' => '2023-01-01 10:00:00',
                'gender' => 'L'
            ],
            [
                'NIK' => '1234567890123456',
                'name' => 'Andi Setiawan',
                'phone_number' => '081234567890',
                'address' => 'Jl. Merdeka No. 1, Surabaya',
                'role' => 'admin',
                'birthdate' => null,
                'profile' => 'profile1.jpg',
                'email' => 'andi.setiawan@example.com',
                'email_verified_at' => '2023-01-02 12:00:00',
                'password' => Hash::make('hashed_password_1'),
                'google_id' => 'google_id_1',
                'google_token' => 'google_token_1',
                'google_refresh_token' => 'google_refresh_token_1',
                'remember_token' => 'remember_token_1',
                'created_at' => '2023-01-01 10:00:00',
                'updated_at' => '2023-01-01 10:00:00',
                'gender' => 'L'
            ],
            [
                'NIK' => '1234567890123457',
                'name' => 'Budi Santoso',
                'phone_number' => '081234567891',
                'address' => 'Jl. Pahlawan No. 2, Surabaya',
                'role' => 'user',
                'birthdate' => null,
                'profile' => 'profile2.jpg',
                'email' => 'budi.santoso@example.com',
                'email_verified_at' => '2023-01-02 12:00:00',
                'password' => Hash::make('hashed_password_2'),
                'google_id' => 'google_id_2',
                'google_token' => 'google_token_2',
                'google_refresh_token' => 'google_refresh_token_2',
                'remember_token' => 'remember_token_2',
                'created_at' => '2023-01-02 10:00:00',
                'updated_at' => '2023-01-02 10:00:00',
                'gender' => 'L'
            ],
            [
                'NIK' => '1234567890123458',
                'name' => 'Citra Dewi',
                'phone_number' => '081234567892',
                'address' => 'Jl. Cinta No. 3, Surabaya',
                'role' => 'user',
                'birthdate' => null,
                'profile' => 'profile3.jpg',
                'email' => 'citra.dewi@example.com',
                'email_verified_at' => '2023-01-03 14:00:00',
                'password' => Hash::make('hashed_password_3'),
                'google_id' => 'google_id_3',
                'google_token' => 'google_token_3',
                'google_refresh_token' => 'google_refresh_token_3',
                'remember_token' => 'remember_token_3',
                'created_at' => '2023-01-03 10:00:00',
                'updated_at' => '2023-01-03 10:00:00',
                'gender' => 'P'
            ],
            [
                'NIK' => '1234567890123459',
                'name' => 'Dedi Prasetyo',
                'phone_number' => '081234567893',
                'address' => 'Jl. Kebangsaan No. 4, Surabaya',
                'role' => 'user',
                'birthdate' => null,
                'profile' => 'profile4.jpg',
                'email' => 'dedi.prasetyo@example.com',
                'email_verified_at' => '2023-01-02 12:00:00',
                'password' => Hash::make('hashed_password_4'),
                'google_id' => 'google_id_4',
                'google_token' => 'google_token_4',
                'google_refresh_token' => 'google_refresh_token_4',
                'remember_token' => 'remember_token_4',
                'created_at' => '2023-01-04 10:00:00',
                'updated_at' => '2023-01-04 10:00:00',
                'gender' => 'L'
            ],
            [
                'NIK' => '1234567890123460',
                'name' => 'Eka Putri',
                'phone_number' => '081234567894',
                'address' => 'Jl. Harapan No. 5, Surabaya',
                'role' => 'user',
                'birthdate' => null,
                'profile' => 'profile5.jpg',
                'email' => 'eka.putri@example.com',
                'email_verified_at' => '2023-01-05 16:00:00',
                'password' => Hash::make('hashed_password_5'),
                'google_id' => 'google_id_5',
                'google_token' => 'google_token_5',
                'google_refresh_token' => 'google_refresh_token_5',
                'remember_token' => 'remember_token_5',
                'created_at' => '2023-01-05 10:00:00',
                'updated_at' => '2023-01-05 10:00:00',
                'gender' => 'P'
            ],
            [
                'NIK' => '1234567890123461',
                'name' => 'Fajar Setiawan',
                'phone_number' => '081234567895',
                'address' => 'Jl. Bunga No. 6, Surabaya',
                'role' => 'user',
                'birthdate' => null,
                'profile' => 'profile6.jpg',
                'email' => 'fajar.setiawan@example.com',
                'email_verified_at' => '2023-01-02 12:00:00',
                'password' => Hash::make('hashed_password_6'),
                'google_id' => 'google_id_6',
                'google_token' => 'google_token_6',
                'google_refresh_token' => 'google_refresh_token_6',
                'remember_token' => 'remember_token_6',
                'created_at' => '2023-01-06 10:00:00',
                'updated_at' => '2023-01-06 10:00:00',
                'gender' => 'L'
            ],
            [
                'NIK' => '1234567890123462',
                'name' => 'Gita Sari',
                'phone_number' => '081234567896',
                'address' => 'Jl. Cendana No. 7, Surabaya',
                'role' => 'user',
                'birthdate' => null,
                'profile' => 'profile7.jpg',
                'email' => 'gita.sari@example.com',
                'email_verified_at' => '2023-01-07 12:00:00',
                'password' => Hash::make('hashed_password_7'),
                'google_id' => 'google_id_7',
                'google_token' => 'google_token_7',
                'google_refresh_token' => 'google_refresh_token_7',
                'remember_token' => 'remember_token_7',
                'created_at' => '2023-01-07 10:00:00',
                'updated_at' => '2023-01-07 10:00:00',
                'gender' => 'P'
            ],
            [
                'NIK' => '1234567890123463',
                'name' => 'Hadi Pratama',
                'phone_number' => '081234567897',
                'address' => 'Jl. Anggrek No. 8, Surabaya',
                'role' => 'user',
                'birthdate' => null,
                'profile' => 'profile8.jpg',
                'email' => 'hadi.pratama@example.com',
                'email_verified_at' => '2023-01-02 12:00:00',
                'password' => Hash::make('hashed_password_8'),
                'google_id' => 'google_id_8',
                'google_token' => 'google_token_8',
                'google_refresh_token' => 'google_refresh_token_8',
                'remember_token' => 'remember_token_8',
                'created_at' => '2023-01-08 10:00:00',
                'updated_at' => '2023-01-08 10:00:00',
                'gender' => 'L'
            ],
            [
                'NIK' => '1234567890123464',
                'name' => 'Ika Lestari',
                'phone_number' => '081234567898',
                'address' => 'Jl. Melati No. 9, Surabaya',
                'role' => 'user',
                'birthdate' => null,
                'profile' => 'profile9.jpg',
                'email' => 'ika.lestari@example.com',
                'email_verified_at' => '2023-01-09 14:00:00',
                'password' => Hash::make('hashed_password_9'),
                'google_id' => 'google_id_9',
                'google_token' => 'google_token_9',
                'google_refresh_token' => 'google_refresh_token_9',
                'remember_token' => 'remember_token_9',
                'created_at' => '2023-01-09 10:00:00',
                'updated_at' => '2023-01-09 10:00:00',
                'gender' => 'P'
            ],
            [
                'NIK' => '1234567890123465',
                'name' => 'Joko Widodo',
                'phone_number' => '081234567899',
                'address' => 'Jl. Kenanga No. 10, Surabaya',
                'role' => 'user',
                'birthdate' => null,
                'profile' => 'profile10.jpg',
                'email' => 'joko.widodo@example.com',
                'email_verified_at' => '2023-01-02 12:00:00',
                'password' => Hash::make('hashed_password_10'),
                'google_id' => 'google_id_10',
                'google_token' => 'google_token_10',
                'google_refresh_token' => 'google_refresh_token_10',
                'remember_token' => 'remember_token_10',
                'created_at' => '2023-01-10 10:00:00',
                'updated_at' => '2023-01-10 10:00:00',
                'gender' => 'L'
            ],
            [
                'NIK' => '3578900000000013',
                'name' => 'Dr. Ahmad Fauzi',
                'phone_number' => '081210000001',
                'address' => 'Jl. Kesehatan No. 1',
                'role' => 'Dokter',
                'birthdate' => '1980-01-15',
                'profile' => 'dr_ahmad.jpg',
                'email' => 'dr.ahmad@example.com',
                'gender' => 'L',
                'email_verified_at' => now(),
                'password' => Hash::make('dokter123'),
                'google_id' => null,
                'google_token' => null,
                'google_refresh_token' => null,
                'remember_token' => Str::random(20),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'NIK' => '3578900000000014',
                'name' => 'Dr. Budi Santoso',
                'phone_number' => '081210000002',
                'address' => 'Jl. Sehat Selalu No. 2',
                'role' => 'Dokter',
                'birthdate' => '1979-06-12',
                'profile' => 'dr_budi.jpg',
                'email' => 'dr.budi@example.com',
                'gender' => 'L',
                'email_verified_at' => now(),
                'password' => Hash::make('dokter123'),
                'google_id' => null,
                'google_token' => null,
                'google_refresh_token' => null,
                'remember_token' => Str::random(20),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'NIK' => '3578900000000015',
                'name' => 'Dr. Cinta Dewi',
                'phone_number' => '081210000003',
                'address' => 'Jl. Kasih Sayang No. 3',
                'role' => 'Dokter',
                'birthdate' => '1983-04-10',
                'profile' => 'dr_cinta.jpg',
                'email' => 'dr.cinta@example.com',
                'gender' => 'P',
                'email_verified_at' => now(),
                'password' => Hash::make('dokter123'), // gunakan Hash::make jika di seeder
                'google_id' => null,
                'google_token' => null,
                'google_refresh_token' => null,
                'remember_token' => Str::random(20),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'NIK' => '3578900000000016',
                'name' => 'Dr. Dedi Prasetyo',
                'phone_number' => '081210000016',
                'address' => 'Jl. Medika No. 16',
                'role' => 'Dokter',
                'birthdate' => '1985-03-21',
                'profile' => 'dr_dedi.jpg',
                'email' => 'dr.dedi@example.com',
                'gender' => 'L',
                'email_verified_at' => now(),
                'password' => Hash::make('dokter123'),
                'google_id' => null,
                'google_token' => null,
                'google_refresh_token' => null,
                'remember_token' => Str::random(20),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'NIK' => '3578900000000017',
                'name' => 'Dr. Eka Putri',
                'phone_number' => '081210000017',
                'address' => 'Jl. Pertiwi No. 17',
                'role' => 'Dokter',
                'birthdate' => '1986-07-10',
                'profile' => 'dr_eka.jpg',
                'email' => 'dr.eka@example.com',
                'gender' => 'P',
                'email_verified_at' => now(),
                'password' => Hash::make('dokter123'),
                'google_id' => null,
                'google_token' => null,
                'google_refresh_token' => null,
                'remember_token' => Str::random(20),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'NIK' => '3578900000000018',
                'name' => 'Dr. Fajar Setiawan',
                'phone_number' => '081210000018',
                'address' => 'Jl. Mentari No. 18',
                'role' => 'Dokter',
                'birthdate' => '1982-11-25',
                'profile' => 'dr_fajar.jpg',
                'email' => 'dr.fajar@example.com',
                'gender' => 'L',
                'email_verified_at' => now(),
                'password' => Hash::make('dokter123'),
                'google_id' => null,
                'google_token' => null,
                'google_refresh_token' => null,
                'remember_token' => Str::random(20),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'NIK' => '3578900000000019',
                'name' => 'Dr. Gita Sari',
                'phone_number' => '081210000019',
                'address' => 'Jl. Mawar Putih No. 19',
                'role' => 'Dokter',
                'birthdate' => '1987-05-14',
                'profile' => 'dr_gita.jpg',
                'email' => 'dr.gita@example.com',
                'gender' => 'P',
                'email_verified_at' => now(),
                'password' => Hash::make('dokter123'),
                'google_id' => null,
                'google_token' => null,
                'google_refresh_token' => null,
                'remember_token' => Str::random(20),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'NIK' => '3578900000000020',
                'name' => 'Dr. Hadi Pratama',
                'phone_number' => '081210000020',
                'address' => 'Jl. Surya Harapan No. 20',
                'role' => 'Dokter',
                'birthdate' => '1980-10-22',
                'profile' => 'dr_hadi.jpg',
                'email' => 'dr.hadi@example.com',
                'gender' => 'L',
                'email_verified_at' => now(),
                'password' => Hash::make('dokter123'),
                'google_id' => null,
                'google_token' => null,
                'google_refresh_token' => null,
                'remember_token' => Str::random(20),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'NIK' => '3578900000000021',
                'name' => 'Dr. Ika Lestari',
                'phone_number' => '081210000021',
                'address' => 'Jl. Anggrek Indah No. 21',
                'role' => 'Dokter',
                'birthdate' => '1990-01-05',
                'profile' => 'dr_ika.jpg',
                'email' => 'dr.ika@example.com',
                'gender' => 'P',
                'email_verified_at' => now(),
                'password' => Hash::make('dokter123'),
                'google_id' => null,
                'google_token' => null,
                'google_refresh_token' => null,
                'remember_token' => Str::random(20),
                'created_at' => now(),
                'updated_at' => now(),
            ], 
            [
                'NIK' => '3578900000000023',
                'name' => 'Dr. Kiki Suryadi',
                'phone_number' => '081210000023',
                'address' => 'Jl. Damai No. 23',
                'role' => 'Dokter',
                'birthdate' => '1991-06-30',
                'profile' => 'dr_kiki.jpg',
                'email' => 'dr.kiki@example.com',
                'gender' => 'L',
                'email_verified_at' => now(),
                'password' => Hash::make('dokter123'),
                'google_id' => null,
                'google_token' => null,
                'google_refresh_token' => null,
                'remember_token' => Str::random(20),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'NIK' => '3578900000000024',
                'name' => 'Dr. Lina Wati',
                'phone_number' => '081210000024',
                'address' => 'Jl. Sehat Sentosa No. 24',
                'role' => 'Dokter',
                'birthdate' => '1984-04-18',
                'profile' => 'dr_lina.jpg',
                'email' => 'dr.lina@example.com',
                'gender' => 'P',
                'email_verified_at' => now(),
                'password' => Hash::make('dokter123'),
                'google_id' => null,
                'google_token' => null,
                'google_refresh_token' => null,
                'remember_token' => Str::random(20),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'NIK' => '3578900000000025',
                'name' => 'Dr. Mira Sari',
                'phone_number' => '081210000025',
                'address' => 'Jl. Kesehatan No. 25',
                'role' => 'Dokter',
                'birthdate' => '1988-12-07',
                'profile' => 'dr_mira.jpg',
                'email' => 'dr.mira@example.com',
                'gender' => 'P',
                'email_verified_at' => now(),
                'password' => Hash::make('dokter123'),
                'google_id' => null,
                'google_token' => null,
                'google_refresh_token' => null,
                'remember_token' => Str::random(20),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'NIK' => '3578900000000026',
                'name' => 'Dr. Oki Prasetyo',
                'phone_number' => '081210000026',
                'address' => 'Jl. Damai Lestari No. 27',
                'role' => 'Dokter',
                'gender' => 'L',
                'birthdate' => '1985-06-12',
                'profile' => 'dr_oki.jpg',
                'email' => 'dr.oki@example.com',
                'email_verified_at' => now(),
                'password' => Hash::make('dokter123'),
                'google_id' => null,
                'google_token' => null,
                'google_refresh_token' => null,
                'remember_token' => Str::random(20),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'NIK' => '3578900000000027',
                'name' => 'Dr. Nani Lestari',
                'phone_number' => '081210000027',
                'address' => 'Jl. Teratai No. 26',
                'role' => 'Dokter',
                'birthdate' => '1986-08-30',
                'profile' => 'dr_nani.jpg',
                'email' => 'dr.nani@example.com',
                'gender' => 'P',
                'email_verified_at' => now(),
                'password' => Hash::make('dokter123'),
                'google_id' => null,
                'google_token' => null,
                'google_refresh_token' => null,
                'remember_token' => Str::random(20),
                'created_at' => now(),
                'updated_at' => now(),
            ],
                                   
        ]);
    }
}
