<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('users')->insert([
            [
                'NIK' => '1234567890123456',
                'name' => 'Admin1',
                'phone_number' => '081234567890',
                'address' => 'Jl. Merdeka No. 1, Surabaya',
                'role' => 'admin',
                'profile' => 'profile1.jpg',
                'email' => 'admin1@example.com',
                'email_verified_at' => null,
                'password' => '123456789',
                'google_id' => 'google_id_1',
                'google_token' => 'google_token_1',
                'google_refresh_token' => 'google_refresh_token_1',
                'remember_token' => 'remember_token_1',
                'created_at' => '2023-01-01 10:00:00',
                'updated_at' => '2023-01-01 10:00:00',
                'gender' => 'L'
            ],
            [
                'NIK' => '1234567890123456',
                'name' => 'Admin2',
                'phone_number' => '081234567890',
                'address' => 'Jl. Merdeka No. 1, Surabaya',
                'role' => 'admin',
                'profile' => 'profile1.jpg',
                'email' => 'admin2@example.com',
                'email_verified_at' => null,
                'password' => '123456789',
                'google_id' => 'google_id_1',
                'google_token' => 'google_token_1',
                'google_refresh_token' => 'google_refresh_token_1',
                'remember_token' => 'remember_token_1',
                'created_at' => '2023-01-01 10:00:00',
                'updated_at' => '2023-01-01 10:00:00',
                'gender' => 'L'
            ],
            [
                'NIK' => '1234567890123456',
                'name' => 'Andi Setiawan',
                'phone_number' => '081234567890',
                'address' => 'Jl. Merdeka No. 1, Surabaya',
                'role' => 'admin',
                'profile' => 'profile1.jpg',
                'email' => 'andi.setiawan@example.com',
                'email_verified_at' => null,
                'password' => 'hashed_password_1',
                'google_id' => 'google_id_1',
                'google_token' => 'google_token_1',
                'google_refresh_token' => 'google_refresh_token_1',
                'remember_token' => 'remember_token_1',
                'created_at' => '2023-01-01 10:00:00',
                'updated_at' => '2023-01-01 10:00:00',
                'gender' => 'L'
            ],
            [
                'NIK' => '1234567890123457',
                'name' => 'Budi Santoso',
                'phone_number' => '081234567891',
                'address' => 'Jl. Pahlawan No. 2, Surabaya',
                'role' => 'user',
                'profile' => 'profile2.jpg',
                'email' => 'budi.santoso@example.com',
                'email_verified_at' => '2023-01-02 12:00:00',
                'password' => 'hashed_password_2',
                'google_id' => 'google_id_2',
                'google_token' => 'google_token_2',
                'google_refresh_token' => 'google_refresh_token_2',
                'remember_token' => 'remember_token_2',
                'created_at' => '2023-01-02 10:00:00',
                'updated_at' => '2023-01-02 10:00:00',
                'gender' => 'L'
            ],
            [
                'NIK' => '1234567890123458',
                'name' => 'Citra Dewi',
                'phone_number' => '081234567892',
                'address' => 'Jl. Cinta No. 3, Surabaya',
                'role' => 'user',
                'profile' => 'profile3.jpg',
                'email' => 'citra.dewi@example.com',
                'email_verified_at' => '2023-01-03 14:00:00',
                'password' => 'hashed_password_3',
                'google_id' => 'google_id_3',
                'google_token' => 'google_token_3',
                'google_refresh_token' => 'google_refresh_token_3',
                'remember_token' => 'remember_token_3',
                'created_at' => '2023-01-03 10:00:00',
                'updated_at' => '2023-01-03 10:00:00',
                'gender' => 'P'
            ],
            [
                'NIK' => '1234567890123459',
                'name' => 'Dedi Prasetyo',
                'phone_number' => '081234567893',
                'address' => 'Jl. Kebangsaan No. 4, Surabaya',
                'role' => 'user',
                'profile' => 'profile4.jpg',
                'email' => 'dedi.prasetyo@example.com',
                'email_verified_at' => null,
                'password' => 'hashed_password_4',
                'google_id' => 'google_id_4',
                'google_token' => 'google_token_4',
                'google_refresh_token' => 'google_refresh_token_4',
                'remember_token' => 'remember_token_4',
                'created_at' => '2023-01-04 10:00:00',
                'updated_at' => '2023-01-04 10:00:00',
                'gender' => 'L'
            ],
            [
                'NIK' => '1234567890123460',
                'name' => 'Eka Putri',
                'phone_number' => '081234567894',
                'address' => 'Jl. Harapan No. 5, Surabaya',
                'role' => 'user',
                'profile' => 'profile5.jpg',
                'email' => 'eka.putri@example.com',
                'email_verified_at' => '2023-01-05 16:00:00',
                'password' => 'hashed_password_5',
                'google_id' => 'google_id_5',
                'google_token' => 'google_token_5',
                'google_refresh_token' => 'google_refresh_token_5',
                'remember_token' => 'remember_token_5',
                'created_at' => '2023-01-05 10:00:00',
                'updated_at' => '2023-01-05 10:00:00',
                'gender' => 'P'
            ],
            [
                'NIK' => '1234567890123461',
                'name' => 'Fajar Setiawan',
                'phone_number' => '081234567895',
                'address' => 'Jl. Bunga No. 6, Surabaya',
                'role' => 'user',
                'profile' => 'profile6.jpg',
                'email' => 'fajar.setiawan@example.com',
                'email_verified_at' => null,
                'password' => 'hashed_password_6',
                'google_id' => 'google_id_6',
                'google_token' => 'google_token_6',
                'google_refresh_token' => 'google_refresh_token_6',
                'remember_token' => 'remember_token_6',
                'created_at' => '2023-01-06 10:00:00',
                'updated_at' => '2023-01-06 10:00:00',
                'gender' => 'L'
            ],
            [
                'NIK' => '1234567890123462',
                'name' => 'Gita Sari',
                'phone_number' => '081234567896',
                'address' => 'Jl. Cendana No. 7, Surabaya',
                'role' => 'user',
                'profile' => 'profile7.jpg',
                'email' => 'gita.sari@example.com',
                'email_verified_at' => '2023-01-07 12:00:00',
                'password' => 'hashed_password_7',
                'google_id' => 'google_id_7',
                'google_token' => 'google_token_7',
                'google_refresh_token' => 'google_refresh_token_7',
                'remember_token' => 'remember_token_7',
                'created_at' => '2023-01-07 10:00:00',
                'updated_at' => '2023-01-07 10:00:00',
                'gender' => 'P'
            ],
            [
                'NIK' => '1234567890123463',
                'name' => 'Hadi Pratama',
                'phone_number' => '081234567897',
                'address' => 'Jl. Anggrek No. 8, Surabaya',
                'role' => 'user',
                'profile' => 'profile8.jpg',
                'email' => 'hadi.pratama@example.com',
                'email_verified_at' => null,
                'password' => 'hashed_password_8',
                'google_id' => 'google_id_8',
                'google_token' => 'google_token_8',
                'google_refresh_token' => 'google_refresh_token_8',
                'remember_token' => 'remember_token_8',
                'created_at' => '2023-01-08 10:00:00',
                'updated_at' => '2023-01-08 10:00:00',
                'gender' => 'L'
            ],
            [
                'NIK' => '1234567890123464',
                'name' => 'Ika Lestari',
                'phone_number' => '081234567898',
                'address' => 'Jl. Melati No. 9, Surabaya',
                'role' => 'user',
                'profile' => 'profile9.jpg',
                'email' => 'ika.lestari@example.com',
                'email_verified_at' => '2023-01-09 14:00:00',
                'password' => 'hashed_password_9',
                'google_id' => 'google_id_9',
                'google_token' => 'google_token_9',
                'google_refresh_token' => 'google_refresh_token_9',
                'remember_token' => 'remember_token_9',
                'created_at' => '2023-01-09 10:00:00',
                'updated_at' => '2023-01-09 10:00:00',
                'gender' => 'P'
            ],
            [
                'NIK' => '1234567890123465',
                'name' => 'Joko Widodo',
                'phone_number' => '081234567899',
                'address' => 'Jl. Kenanga No. 10, Surabaya',
                'role' => 'user',
                'profile' => 'profile10.jpg',
                'email' => 'joko.widodo@example.com',
                'email_verified_at' => null,
                'password' => 'hashed_password_10',
                'google_id' => 'google_id_10',
                'google_token' => 'google_token_10',
                'google_refresh_token' => 'google_refresh_token_10',
                'remember_token' => 'remember_token_10',
                'created_at' => '2023-01-10 10:00:00',
                'updated_at' => '2023-01-10 10:00:00',
                'gender' => 'L'
            ]
        ]);
    }
}
